# prometheus.yml - na RAIZ do projeto
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']
    scrape_interval: 5s

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['172.17.0.1:8889']
    scrape_interval: 10s
    metrics_path: /metrics

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'telemetry-service'
    static_configs:
      - targets: ['172.17.0.1:8026', '172.17.0.1:8027']