server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: myapp
    static_configs:  # 🔥 CORRIGIDO: static_configs (com S)
      - targets:
          - localhost
        labels:
          job: myapp
          environment: development
          __path__: /var/log/myapp/*.log
  - job_name: app-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: node-app
          __path__: /var/log/app/*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            message: message
            requestId: requestId
            method: method
            url: url
            statusCode: statusCode
            duration: duration
      - labels:
          level:
          method:
          statusCode: